esphome:
  name: esphome-web-e01766
  friendly_name: Audi Quattro
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
captive_portal:

# Define GPIO outputs for LEDs
output:
  - platform: gpio
    pin: GPIO5     # D1
    id: led_front
  - platform: gpio
    pin: GPIO4     # D2
    id: led_back
  - platform: gpio
    pin: GPIO14    # D5
    id: led_interior

# Expose them as switches
light:
  - platform: binary
    name: "Front"
    id: front_led_light
    output: led_front

  - platform: binary
    name: "Back"
    id: back_led_light
    output: led_back

  - platform: binary
    name: "Interior"
    id: interior_led_light
    output: led_interior

# all lights toggle
switch:
  - platform: template
    name: "All Lights"
    id: all_leds_light
    lambda: |-
      if (id(front_led_light).current_values.is_on() ||
          id(back_led_light).current_values.is_on() ||
          id(interior_led_light).current_values.is_on()) {
        return true;  // Show ON if any light is on
      } else {
        return false; // Show OFF only if all are off
      }
    turn_on_action:
      - light.turn_on: front_led_light
      - light.turn_on: back_led_light
      - light.turn_on: interior_led_light
    turn_off_action:
      - light.turn_off: front_led_light
      - light.turn_off: back_led_light
      - light.turn_off: interior_led_light

