esphome:
  name: esphome-web-e01766
  friendly_name: Audi Quattro
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
captive_portal:

# Define GPIO outputs for LEDs
output:
  - platform: gpio
    pin: GPIO5     # D1
    id: led_front
  - platform: gpio
    pin: GPIO4     # D2
    id: led_back
  - platform: gpio
    pin: GPIO14    # D5
    id: led_interior

# Expose them as switches
switch:
  - platform: output
    name: "Front LED"
    output: led_front
  - platform: output
    name: "Back LED"
    output: led_back
  - platform: output
    name: "Interior LED"
    output: led_interior